version: "3.8"

services:
  #####################################################
  # CAdvisor
  #####################################################
  cadvisor:
    profiles: ["cadvisor"]
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 18080:18080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    profiles: ["cadvisor"]
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  #####################################################
  # Apache Hadoop
  #####################################################
  namenode:
    build:
      context: .
      dockerfile: ./docker/hadoop/hadoop-namenode/Dockerfile
    image: keyhong/namenode-v1.0.0
    container_name: namenode
    expose:
      - "10000" # HDFS Namenode RPC
    ports:
      - "9870:9870" # HDFS Namenode Web Http
    volumes:
      - ./mnt/hadoop/namenode:/data/hadoop/dfs/name
    environment:
      CLUSTER_NAME: hadoop_cluster
    healthcheck:
      test: [ "CMD", "nc", "-z", "namenode", "9870" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped

  datanode:
    build:
      context: .
      dockerfile: ./docker/hadoop/hadoop-datanode/Dockerfile
    image: keyhong/datanode-v1.0.0
    container_name: datanode
    expose:
      - "9864" # HDFS Datanode RPC
    depends_on:
      - namenode
    volumes:
      - ./mnt/hadoop/datanode:/data/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    healthcheck:
      test: [ "CMD", "nc", "-z", "datanode", "9864" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped

  #####################################################
  # MySQL
  #####################################################
  mysql:
    image: mysql:8.0.36-bullseye
    container_name: mysql
    env_file:
      - ./.envs/.local/.mysql
    environment:
      TZ: Asia/Seoul
    ports:
      - 13306:3306
    volumes:
      - ./mnt/mysql:/var/lib/mysql
      - ./init-sql/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      timeout: 45s
      interval: 10s
      retries: 10
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    restart: unless-stopped
    
  #####################################################
  # Apache Hive
  #####################################################
  hive-metastore:
    profiles: ["hive"]
    build:
      context: .
      dockerfile: ./docker/hive/hive-metastore/Dockerfile
    image: keyhong/hive-metastore-v1.0.0
    container_name: hive-metastore
    depends_on:
      - namenode
      - datanode
      - mysql
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 mysql:3306"
    volumes:
      - ./mnt/schematool-check:/schematool-check     
    ports:
      - "9083:9083" # Hive Metastore Server
    healthcheck:
      test: [ "CMD", "nc", "-z", "hive-metastore", "9083" ]
      timeout: 45s
      interval: 10s
    restart: unless-stopped

  hive-server:
    profiles: ["hive-server"]
    build:
      context: .
      dockerfile: ./docker/hive/hive-server/Dockerfile
    image: keyhong/hive-server-v1.0.0
    container_name: hive-server
    depends_on:
      - hive-metastore
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000" # HiveServer2 Client
      - "10002:10002" # HiveServer2 Web UI
    healthcheck:
      test: [ "CMD", "nc", "-z", "hive-server", "10002" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped

  hive-webhcat:
    profiles: ["hive-webhcat"]
    build:
      context: .
      dockerfile: ./docker/hive/hive-webhcat/Dockerfile
    image: keyhong/hive-webhcat-v1.0.0
    
    container_name: hive-webhcat
    expose:
      - "50111"
    depends_on:
      - hive-server
    environment:
      - SERVICE_PRECONDITION=hive-server:10000
    healthcheck:
      test: [ "CMD", "nc", "-z", "hive-webhcat", "50111" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped

  #####################################################
  # Hue
  #####################################################
  hue:
    profiles: ["hue"]
    build: ./docker/hue
    container_name: hue
    depends_on:
      - hive-server
      - mysql
    ports:
      - "8888:8888"
    volumes:
      - ./mnt/hue/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    environment:
      - SERVICE_PRECONDITION=hive-server:10000 mysql:3306
    healthcheck:
      test: [ "CMD", "nc", "-z", "hue", "8888" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped

  #####################################################
  # DBT
  #####################################################
  dbt-workspace:
    profiles: ["dbt"]
    image: python:3.10.13-slim-bullseye
    container_name: dbt
    command: ["sleep", "6000000"]
    volumes:
      - ./dbt:/root/

  #####################################################
  # Apache Kudu
  #####################################################
  kudu-master:
    profiles: ["kudu"]
    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
    container_name: kudu-master
    ports:
      - "7051:7051"
      - "8051:8051"
    command: ["master"]
    volumes:
      - kudu-master-v:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master:7051
      - >
        MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
        --rpc_bind_addresses=0.0.0.0:7051
        --rpc_advertised_addresses=host.docker.internal:7051
        --webserver_advertised_addresses=host.docker.internal:8051
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false
        --unlock_unsafe_flags=true
        --default_num_replicas=1

  kudu-tserver:
    profiles: ["kudu"]
    image: apache/kudu:${KUDU_QUICKSTART_VERSION:-latest}
    container_name: kudu-tserver
    depends_on:
      - kudu-master
    ports:
      - "7050:7050"
      - "8050:8050"
    command: ["tserver"]
    volumes:
      - kudu-tserver-v:/var/lib/kudu
    environment:
      - KUDU_MASTERS=kudu-master:7051
      - >
        TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
        --rpc_bind_addresses=0.0.0.0:7050
        --rpc_advertised_addresses=host.docker.internal:7050
        --webserver_advertised_addresses=localhost:8050
        --webserver_doc_root=/opt/kudu/www
        --stderrthreshold=0
        --use_hybrid_clock=false
        --unlock_unsafe_flags=true
        --default_num_replicas=1

  #####################################################
  # Trino
  #####################################################
  trino:
    profiles: ["trino"]
    build:
      context: .
      dockerfile: ./docker/trino/Dockerfile
    image: keyhong/trino-v1.0.0
    container_name: trino
    depends_on:
      # - hive-server
      - kudu-tserver
    environment:
      SERVICE_PRECONDITION: "kudu-tserver:3306"
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "nc", "-z", "trino", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped

######################################################
# NETWORK
######################################################
networks:
  default:
    name: hadoop-cluster

volumes:
  kudu-master-v:
  kudu-tserver-v:
